[phases.setup]
nixPkgs = ["...", "libzip", "zlib", "supervisor"]

[phases.install]
cmds = [
    "mkdir -p /etc/php/conf.d",
    "install-php-extensions zip pdo_mysql ctype curl dom fileinfo filter hash mbstring openssl pcre pdo session tokenizer xml gd bcmath",
    "COMPOSER_ALLOW_SUPERUSER=1 composer install --optimize-autoloader --no-dev --no-interaction"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && supervisord -c supervisord.conf"
